apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kuard
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 10
  - name: ng-2
    instanceType: t2.medium
    desiredCapacity: 2
